name: Nightly test Workflow

on:
  schedule:
    - cron: "0 2 * * *" # This schedules the workflow to run at 02:00 UTC every day
  # TODO remove PR run
  pull_request:

jobs:
  list-yamls:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls ./.github/tests/*.yaml | jq -R -s -c 'split("\n")[:-1]')"
  run_with_args:
    needs: list-yamls
    strategy:
      matrix:
          file_name: ${{ fromJson(needs.list-yamls.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis analytics disable

      - name: Run Starlark
        run: kurtosis run ${{ github.workspace }} --args-file ${{ matrix.file_name }}
