name: CI

on:
  pull_request:

concurrency:
  group: "tests-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  run_starlark:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Kurtosis
        uses: ./.github/actions/kurtosis-install
      - name: Run Starlark
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          kurtosis run ${{ github.workspace }} --args-file network_params.yaml

  run_with_args:
    strategy:
      matrix:
        file_name:
          [
            "./.github/tests/mev.yaml",
            "./.github/tests/mev-mock.yaml",
            "./.github/tests/mix-with-tools.yaml",
            "./.github/tests/mix-persistence.yaml",
            "./.github/tests/mix-public.yaml",
            "./.github/tests/minimal.yaml",
            "./network_params.yaml"
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Kurtosis
        uses: ./.github/actions/kurtosis-install
      - name: Run Starlark
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          kurtosis run ${{ github.workspace }} --args-file ${{ matrix.file_name }}

  lint:
    runs-on: self-hosted-ghr-size-s-x64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Kurtosis
        uses: ./.github/actions/kurtosis-install
      - name: Kurtosis Lint
        run: kurtosis lint ${{ github.workspace }}

  assertoor:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Kurtosis Assertoor GitHub Action
        uses: ethpandaops/kurtosis-assertoor-github-action@v1
        with:
          ethereum_package_url: "."
          ethereum_package_branch: ""
          ethereum_package_args: .github/tests/mix-assert.yaml
